name: jshint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: apt
      run: sudo apt-get install -y nodejs npm

    - name: jshint install
      run: sudo npm i -g jshint

    - name: jshint run
      run: jshint src
